<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Courses</title>
</head>
<body>
    <table>
        <?php foreach ($courses as $course): ?>
            <tr>
                <td><?= htmlspecialchars($course['id']) ?>.</td>
                <td><?= htmlspecialchars($course['name']) ?></td>
            </tr>
        <?php endforeach ?>
    </table>
</body>
</html>