<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="/css/styles.css">
    <title>404</title>
</head>
<body>
    <h1>Nu ty zaebal</h1>
    <div>
        <p>User with <?= htmlspecialchars($id)?> not found</p>
        <p>Ne sushestvuet ego DOLBAEB</p>
        <h3 class="f404">404</h3>
    </div>
</body>
</html>